// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * ClusterImageCatalog is the Schema for the clusterimagecatalogs API
 */
export class ClusterImageCatalog extends pulumi.CustomResource {
    /**
     * Get an existing ClusterImageCatalog resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ClusterImageCatalog {
        return new ClusterImageCatalog(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:postgresql.cnpg.io/v1:ClusterImageCatalog';

    /**
     * Returns true if the given object is an instance of ClusterImageCatalog.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterImageCatalog {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterImageCatalog.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"postgresql.cnpg.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"ClusterImageCatalog" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * Specification of the desired behavior of the ClusterImageCatalog.
     * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    public readonly spec!: pulumi.Output<outputs.postgresql.v1.ClusterImageCatalogSpec>;

    /**
     * Create a ClusterImageCatalog resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClusterImageCatalogArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "postgresql.cnpg.io/v1";
            resourceInputs["kind"] = "ClusterImageCatalog";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterImageCatalog.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ClusterImageCatalog resource.
 */
export interface ClusterImageCatalogArgs {
    apiVersion?: pulumi.Input<"postgresql.cnpg.io/v1">;
    kind?: pulumi.Input<"ClusterImageCatalog">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Specification of the desired behavior of the ClusterImageCatalog.
     * More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    spec?: pulumi.Input<inputs.postgresql.v1.ClusterImageCatalogSpecArgs>;
}
