// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * FailoverQuorum contains the information about the current failover
 * quorum status of a PG cluster. It is updated by the instance manager
 * of the primary node and reset to zero by the operator to trigger
 * an update.
 */
export class FailoverQuorum extends pulumi.CustomResource {
    /**
     * Get an existing FailoverQuorum resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FailoverQuorum {
        return new FailoverQuorum(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:postgresql.cnpg.io/v1:FailoverQuorum';

    /**
     * Returns true if the given object is an instance of FailoverQuorum.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FailoverQuorum {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FailoverQuorum.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"postgresql.cnpg.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"FailoverQuorum" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * Most recently observed status of the failover quorum.
     */
    public readonly status!: pulumi.Output<outputs.postgresql.v1.FailoverQuorumStatus | undefined>;

    /**
     * Create a FailoverQuorum resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FailoverQuorumArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "postgresql.cnpg.io/v1";
            resourceInputs["kind"] = "FailoverQuorum";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FailoverQuorum.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FailoverQuorum resource.
 */
export interface FailoverQuorumArgs {
    apiVersion?: pulumi.Input<"postgresql.cnpg.io/v1">;
    kind?: pulumi.Input<"FailoverQuorum">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Most recently observed status of the failover quorum.
     */
    status?: pulumi.Input<inputs.postgresql.v1.FailoverQuorumStatusArgs>;
}
