// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { BackupArgs } from "./backup";
export type Backup = import("./backup").Backup;
export const Backup: typeof import("./backup").Backup = null as any;
utilities.lazyLoad(exports, ["Backup"], () => require("./backup"));

export { ClusterArgs } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export { ClusterImageCatalogArgs } from "./clusterImageCatalog";
export type ClusterImageCatalog = import("./clusterImageCatalog").ClusterImageCatalog;
export const ClusterImageCatalog: typeof import("./clusterImageCatalog").ClusterImageCatalog = null as any;
utilities.lazyLoad(exports, ["ClusterImageCatalog"], () => require("./clusterImageCatalog"));

export { DatabaseArgs } from "./database";
export type Database = import("./database").Database;
export const Database: typeof import("./database").Database = null as any;
utilities.lazyLoad(exports, ["Database"], () => require("./database"));

export { FailoverQuorumArgs } from "./failoverQuorum";
export type FailoverQuorum = import("./failoverQuorum").FailoverQuorum;
export const FailoverQuorum: typeof import("./failoverQuorum").FailoverQuorum = null as any;
utilities.lazyLoad(exports, ["FailoverQuorum"], () => require("./failoverQuorum"));

export { ImageCatalogArgs } from "./imageCatalog";
export type ImageCatalog = import("./imageCatalog").ImageCatalog;
export const ImageCatalog: typeof import("./imageCatalog").ImageCatalog = null as any;
utilities.lazyLoad(exports, ["ImageCatalog"], () => require("./imageCatalog"));

export { PoolerArgs } from "./pooler";
export type Pooler = import("./pooler").Pooler;
export const Pooler: typeof import("./pooler").Pooler = null as any;
utilities.lazyLoad(exports, ["Pooler"], () => require("./pooler"));

export { PublicationArgs } from "./publication";
export type Publication = import("./publication").Publication;
export const Publication: typeof import("./publication").Publication = null as any;
utilities.lazyLoad(exports, ["Publication"], () => require("./publication"));

export { ScheduledBackupArgs } from "./scheduledBackup";
export type ScheduledBackup = import("./scheduledBackup").ScheduledBackup;
export const ScheduledBackup: typeof import("./scheduledBackup").ScheduledBackup = null as any;
utilities.lazyLoad(exports, ["ScheduledBackup"], () => require("./scheduledBackup"));

export { SubscriptionArgs } from "./subscription";
export type Subscription = import("./subscription").Subscription;
export const Subscription: typeof import("./subscription").Subscription = null as any;
utilities.lazyLoad(exports, ["Subscription"], () => require("./subscription"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:postgresql.cnpg.io/v1:Backup":
                return new Backup(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:ClusterImageCatalog":
                return new ClusterImageCatalog(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:Database":
                return new Database(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:FailoverQuorum":
                return new FailoverQuorum(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:ImageCatalog":
                return new ImageCatalog(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:Pooler":
                return new Pooler(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:Publication":
                return new Publication(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:ScheduledBackup":
                return new ScheduledBackup(name, <any>undefined, { urn })
            case "kubernetes:postgresql.cnpg.io/v1:Subscription":
                return new Subscription(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("cloudnative-pg-pulumi", "postgresql.cnpg.io/v1", _module)
