// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Publication is the Schema for the publications API
 */
export class Publication extends pulumi.CustomResource {
    /**
     * Get an existing Publication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Publication {
        return new Publication(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:postgresql.cnpg.io/v1:Publication';

    /**
     * Returns true if the given object is an instance of Publication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Publication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Publication.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"postgresql.cnpg.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"Publication" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * PublicationSpec defines the desired state of Publication
     */
    public readonly spec!: pulumi.Output<outputs.postgresql.v1.PublicationSpec>;
    /**
     * PublicationStatus defines the observed state of Publication
     */
    public readonly status!: pulumi.Output<outputs.postgresql.v1.PublicationStatus | undefined>;

    /**
     * Create a Publication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PublicationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "postgresql.cnpg.io/v1";
            resourceInputs["kind"] = "Publication";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.postgresql.v1.publicationSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Publication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Publication resource.
 */
export interface PublicationArgs {
    apiVersion?: pulumi.Input<"postgresql.cnpg.io/v1">;
    kind?: pulumi.Input<"Publication">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * PublicationSpec defines the desired state of Publication
     */
    spec?: pulumi.Input<inputs.postgresql.v1.PublicationSpecArgs>;
    /**
     * PublicationStatus defines the observed state of Publication
     */
    status?: pulumi.Input<inputs.postgresql.v1.PublicationStatusArgs>;
}
